#!/usr/bin/env python3
"""
build_template_inventory.py — regenerate benchmark_a/template_inventory.{md,csv}
from the released question files and the template module.

Everything it prints is derived, never hand-maintained, so the inventory cannot
drift from the shipped suite. No database is needed.

Usage (from the repository root):
    python tools/build_template_inventory.py
    python tools/build_template_inventory.py --check    # verify, do not write
"""

import argparse
import collections
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS = ROOT / "benchmark_a" / "questions"
HARNESS = ROOT / "benchmark_a" / "harness"

CITY_OF_DATASET = {
    "hamburg_citygml2_lod2_2025.gml": "Hamburg",
    "helsinki_citygml2_lod2_2019.gml": "Helsinki",
    "zurich": "Zurich",
    "nyc": "New York",
    "tokyo": "Tokyo",
}
CITY_ORDER = ["Hamburg", "Helsinki", "Zurich", "New York", "Tokyo"]

CATEGORY_ORDER = ["aggregate", "filter_topk", "multihop", "spatial", "cross_source",
                  "provenance", "coverage", "lod3", "infeasible"]

CATEGORY_CAPABILITY = {
    "aggregate": "schema grounding, standard retrieval",
    "filter_topk": "filters, ranking, compound predicates, missing-value awareness",
    "multihop": "traversal over the compact schema",
    "spatial": "window, proximity, nearest neighbor, geometric multi-hop, 3D structure, density",
    "cross_source": "authoritative against crowd-sourced agreement, gaps in both directions",
    "provenance": "source and confidence constraints, including source-restriction traps",
    "coverage": "partial-coverage-aware aggregation",
    "lod3": "reconstructed facade and interior structure",
    "infeasible": "hallucination resistance, guard-verified absence",
}
WITHHELD = "<withheld: gold query of a held-out test template>"


def read_jsonl(path):
    with path.open(encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def load_templates():
    sys.path.insert(0, str(HARNESS))
    import templates as T                                    # noqa: E402
    return {t["id"]: t for t in T.TEMPLATES}, getattr(T, "REQUIRES", {})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    dev = read_jsonl(QUESTIONS / "dev.jsonl")
    test = read_jsonl(QUESTIONS / "test.jsonl")
    split = {**{r["template_id"]: "dev" for r in dev},
             **{r["template_id"]: "test" for r in test}}
    tpl, requires = load_templates()

    rows, per_cat = [], collections.defaultdict(
        lambda: {"tmpl": 0, "instances": 0, "dev": 0, "test": 0})
    inst = collections.defaultdict(lambda: collections.Counter())
    for r in dev + test:
        inst[r["template_id"]][CITY_OF_DATASET.get(r["dataset"], r["dataset"])] += 1

    for tid, t in tpl.items():
        cities = inst.get(tid, collections.Counter())
        n = sum(cities.values())
        sp = split.get(tid, "not instantiated")
        gold_state = ("refusal (guard query)" if not t.get("feasible")
                      else "withheld" if t.get("gold_cypher") == WITHHELD else "public")
        if not t.get("feasible") and t.get("guard") == WITHHELD:
            gold_state = "refusal (guard withheld)"
        rows.append({
            "template_id": tid,
            "category": t["category"],
            "tier": t["tier"],
            "difficulty": t["difficulty"],
            "feasible": t.get("feasible", True),
            "split": sp,
            "paraphrases": len(t.get("nl", [])),
            "instances": n,
            "cities": " ".join(c for c in CITY_ORDER if cities.get(c)),
            "gold": gold_state,
            "requires": " ".join(requires.get(tid, [])),
        })
        c = per_cat[t["category"]]
        c["tmpl"] += 1
        c["instances"] += n
        c[sp if sp in ("dev", "test") else "dev"] += 0
    for r in dev:
        per_cat[r["category"]]["dev"] += 1
    for r in test:
        per_cat[r["category"]]["test"] += 1

    rows.sort(key=lambda r: (CATEGORY_ORDER.index(r["category"])
                             if r["category"] in CATEGORY_ORDER else 99, r["template_id"]))

    lang = collections.Counter(r.get("lang", "en") for r in dev + test)
    diff = collections.Counter(r["difficulty"] for r in dev + test)
    city = collections.Counter(CITY_OF_DATASET.get(r["dataset"], r["dataset"])
                              for r in dev + test)

    md = ["# Template inventory (generated)",
          "",
          "Generated by `tools/build_template_inventory.py` from "
          "`benchmark_a/questions/{dev,test}.jsonl` and "
          "`benchmark_a/harness/templates.py`. Do not edit by hand.",
          "",
          f"**{len(tpl)} templates, {len(dev) + len(test)} question instances "
          f"({len(dev)} development / {len(test)} held-out test).**",
          "",
          "## By category", "",
          "| Category | Capability probed | Templates | Instances | Dev | Test |",
          "| --- | --- | --: | --: | --: | --: |"]
    for cat in CATEGORY_ORDER:
        if cat not in per_cat:
            continue
        c = per_cat[cat]
        md.append(f"| `{cat}` | {CATEGORY_CAPABILITY.get(cat, '')} | {c['tmpl']} | "
                  f"{c['instances']} | {c['dev']} | {c['test']} |")
    md += ["", "## By city", "",
           "| City | Instances |", "| --- | --: |"]
    for c in CITY_ORDER:
        md.append(f"| {c} | {city.get(c, 0)} |")
    md += ["", "## By authored difficulty", "",
           "| Level | Instances |", "| --: | --: |"]
    for d in sorted(diff):
        md.append(f"| {d} | {diff[d]} |")
    md += ["", "## By language", "",
           "| Language | Instances |", "| --- | --: |"]
    for lg, n in sorted(lang.items(), key=lambda kv: -kv[1]):
        md.append(f"| `{lg}` | {n} |")
    md += ["", "## Every template", "",
           "`gold` is `public` for development templates, `withheld` for held-out test "
           "templates, and `refusal ...` for infeasible templates, whose expected answer "
           "is a refusal and whose guard query proves the absence. `requires` lists the "
           "graph tokens the gold query reads; the generator instantiates a template only "
           "on cities whose measured schema provides them.",
           "",
           "| Template | Cat. | Tier | Diff. | Split | Para. | Inst. | Cities | Gold | Requires |",
           "| --- | --- | --: | --: | --- | --: | --: | --- | --- | --- |"]
    for r in rows:
        md.append(f"| `{r['template_id']}` | {r['category']} | {r['tier']} | "
                  f"{r['difficulty']} | {r['split']} | {r['paraphrases']} | "
                  f"{r['instances']} | {r['cities'] or '(none)'} | {r['gold']} | "
                  f"{('`' + r['requires'] + '`') if r['requires'] else ''} |")
    md_text = "\n".join(md) + "\n"

    out_md = ROOT / "benchmark_a" / "template_inventory.md"
    out_csv = ROOT / "benchmark_a" / "template_inventory.csv"
    if args.check:
        ok = out_md.exists() and out_md.read_text(encoding="utf-8") == md_text
        print("template_inventory.md is up to date" if ok
              else "template_inventory.md is STALE, re-run without --check")
        return 0 if ok else 1

    out_md.write_text(md_text, encoding="utf-8", newline="\n")
    with out_csv.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {out_md.relative_to(ROOT)} and {out_csv.relative_to(ROOT)}: "
          f"{len(rows)} templates, {len(dev) + len(test)} instances")
    return 0


if __name__ == "__main__":
    sys.exit(main())
